-
  name: Install dependecies
  hosts: rpis
  tasks:
    -
      name: install matchbox-keyboard
      become: yes
      apt:
        name: matchbox-keyboard
        state: present
    -
      name: install sqlite3
      become: yes
      apt:
        name: sqlite3
        state: present
    -
      name: install odbc tools for pyodbc
      become: yes
      apt:
        name: unixodbc-dev
        state: present
    -
      name: pip3 install urwid
      pip:
        name: urwid
        executable: pip3
    -
      name: pip3 install pyodbc
      pip:
        name: pyodbc
        executable: pip3
    -
      name: Clone git repository
      git:
        repo: "https://github.com/Reverendheat/apt-floorlocation-python.git"
        dest: /home/pi/aptfloorlocationpython
    -
      name: Edit crontab for heartbeat
      become: yes
      cron:
        name: Add heartbeat
        minute: "*/1"
        job: "sudo /home/pi/aptfloorlocationpython/export.sh >> /home/pi/export.log && python3 /home/pi/aptfloorlocationpython/heartbeat.py"
    -
      name: Edit crontab for wireless
      become: yes
      cron:
        name: Add wireless check
        minute: "*/2"
        job: "sudo /home/pi/aptfloorlocationpython/wlanMonitor.sh >>/home/pi/wlanMonitor.log"
    -
      name: Edit bashrc to start program automagically
      become: yes
      blockinfile:
        path: /home/pi/.bashrc
        insertafter: EOF
        block: |
          echo Starting Floor Inventory Application
          sudo python3 /home/pi/aptfloorlocationpython/APTFloorLocation.py
    -
      name: Change the font size
      become: yes
      replace:
        path: /etc/default/console-setup
        regexp: FONTSIZE=""
        replace: FONTSIZE="16x32"
    -
      name: Change the font face
      become: yes
      replace:
        path: /etc/default/console-setup
        regexp: FONTFACE=""
        replace: FONTFACE="Terminus"
    -
      name: Change hostname
      become: yes
      hostname:
        name: APTPIF
    -
      name: Add wireless SSIDs
      become: yes
      copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600
    -
      name: Add public RSA Key
      become: yes
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '/home/parakoopa/.ssh/id_rsa.pub') }}"
    -
      name: Reboot all pi's
      become: yes
      reboot: 
