-
  name: Install dependecies
  hosts: rpis
  tasks:
    -
      name: Install apt dependencies
      become: yes
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
          - matchbox-keyboard
          - sqlite3
          - unixodbc
          - unixodbc-dev
          - freetds-dev
          - tdsodbc
          - freetds-bin
          - python-pyodbc
    -
      name: pip3 install urwid
      pip:
        name: urwid
        executable: pip3
    -
      name: pip3 install pyodbc
      pip:
        name: pyodbc
        executable: pip3
    -
      name: pip3 install dotenv
      pip:
        name: python-dotenv
        executable: pip3
    -
      name: Clone git repository
      git:
        repo: "https://github.com/Reverendheat/apt-floorlocation-python.git"
        dest: /home/pi/aptfloorlocationpython
    -
      name: remove crontab for heartbeart
      become: yes
      cron:
        name: Add heartbeat
        state: absent
    -
      name: Edit crontab for exports
      become: yes
      cron:
        name: Add exports
        minute: "*/1"
        job: "sudo /home/pi/aptfloorlocationpython/export.sh >> /home/pi/export.log && sudo /home/pi/aptfloorlocationpython/exportwipfl.sh >> /home/pi/exportwipfl.log"
    -
      name: Edit crontab for wireless
      become: yes
      cron:
        name: Add wireless check
        minute: "*/2"
        job: "sudo /home/pi/aptfloorlocationpython/wlanMonitor.sh >>/home/pi/wlanMonitor.log"
    -
      name: Edit crontab for catalog download
      become: yes
      cron:
        name: Add wireless check
        minute: "*/10"
        job: "sudo wget -q -P /home/pi/aptfloorlocationpython/BinDataQty.csv ftp://raspberrypi:Toys.In.Bins.Or.Boxes@NEWMAS/bindata/BinDataQty.csv"
    -
      name: Edit bashrc to start program on logon
      become: yes
      blockinfile:
        path: /home/pi/.bashrc
        insertafter: EOF
        block: |
          echo Starting Floor Inventory Application
          python3 /home/pi/aptfloorlocationpython/APTFloorLocation.py
    -
      name: Change the font size
      become: yes
      replace:
        path: /etc/default/console-setup
        regexp: FONTSIZE=""
        replace: FONTSIZE="14x28"
    -
      name: Change the font face
      become: yes
      replace:
        path: /etc/default/console-setup
        regexp: FONTFACE=""
        replace: FONTFACE="Terminus"
    # -
    #   name: Change hostname
    #   become: yes
    #   hostname:
    #     name: APTPIF
    -
      name: Add wireless SSIDs
      become: yes
      copy:
        backup: yes
        src: ./wpa_supplicant.conf 
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
        mode: '0600'
    -
      name: Add FreeTDS Conf
      become: yes
      copy: 
        backup: yes
        src: ./freetds.conf
        dest: /etc/freetds/freetds.conf
        mode: '0644'
    -
      name: Add ODBC ini
      become: yes
      copy:
        backup: yes
        src: ./odbc.ini
        dest: /etc/odbc.ini
        mode: '0644'
    -
      name: Add ODBCINST ini
      become: yes
      copy:
        backup: yes
        src: ./odbcinst.ini 
        dest: /etc/odbcinst.ini
        mode: '0644'
    -
      name: Add dotenv file
      become: yes
      copy:
        backup: yes
        src: ./.env 
        dest: /home/pi/aptfloorlocationpython/
        mode: '0644'
    -
      name: Add public RSA Key
      become: yes
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '/home/parakoopa/.ssh/id_rsa.pub') }}"
    -
      name: Reboot all pi's
      become: yes
      reboot: